/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {
    	Deck deck = new Deck();	
		Player player = new Player();
		Game game = new Game(deck, player);	
		game.deal();
		game.play();
    }
}
